name: CI
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
    tags:
      - v*
permissions:
  packages: write
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-image
  test-stack:
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/start-stack
        with:
          version: ${{ needs.build-images.outputs.version}}
      - run: docker compose down
  publish-images:
    runs-on: ubuntu-latest
    needs: [build-images, test-stack]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-image
        with:
          target: release
