name: release-please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WREALITY_PAT }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: pilcrow
